# -*- coding: utf-8 -*-
"""Clase8_diccionario_Base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzJyXFtzSzPkveXB7J7Akus8B2Vn_kQQ
"""

#Clase 8
#Ejercicio base
productos={# Cremos un diccionario llamado producto cin algunos articulos
           "Exterior": 45000,
           "Interior": 25000,
           "Exoticas": 45000,
           "Cicca": 78000,
           "Pindo": 40000,
           "Pandurata HG": 120000,
           "Alocassia": 80000,
           "Pandurata HC": 110000,
           "Platycerium" : 87000
           }
# Eleccion de operacion a realizarse
while True:
  print("Elige que tarea queres realizar introduciendo el numero correspondiente")
  print("Eliminar productos: 1. Agregar productos: 2. Ver el valor del producto: 3")
  print("Modificar precios: 4. Agregar productiy valor: 5. Inventario disponible: 6.  ")
  print(" Ver los Prodcutos: 7. Ver los valores: 8. Ver los pares Prodcuti/Valor:9. ")
  print("Borrar Inventario: 10. Salir: 11")
  try:
    respuesta=int(input("Respuesta"))
    # se valida que la entrada sea numeirica con el Try except y con el if
    #que el numero ingresado sea ente 1 y 11
    if respuesta >0 and respuesta < 12:
      break
    else: print("Error. Numero fuera de rango.")
  except ValueError:
    print("Error. Por favor ingrese solo numeros.")
# Eliminar un producto
if respuesta == 1:
                      while True:
                              print("\nIngresá el nombre del producto que querés eliminar (o presioná Enter para terminar):")
                              eliminar = input("Producto a eliminar: ").lower() .title()

   # Si el usuario presiona Enter sin escribir nada, se sale del bucle
                              if eliminar == "":
                                break

   # Verificamos si el producto está en el diccionario y lo eliminamos
                              if eliminar in productos:
                                 productos.pop(eliminar)
                                 print(f"El producto '{eliminar}' fue eliminado del inventario.")
                              else:
                                 print(f"El producto '{eliminar}' no existe en el inventario.")

# Agregar un producto, imprimira al final con valor None

if respuesta ==2:
                  while True:
                           print("\nIngresá el nombre del producto que querés agregar (o presioná Enter para terminar):")
                           incorporado = input("Productoa agregarse: ").lower() .title()
                           if incorporado == "":
                              break
                           if incorporado in productos:
                            print(f"El producto '{incorporado}' ya existe en el inventario.")
                           else:
                             productos.setdefault(incorporado)
                             print(f"El producto '{incorporado}' fue agregado del inventario.")

#  Saber valor de un producto
if respuesta == 3:
                 while True:
                           print("\nIngresá el nombre del producto a saber precio (o presioná Enter para terminar):")
                           getproducto = input("Producto: ").lower().title()
                           if getproducto == "":
                              break
                           if getproducto in productos:
                            #se muestra el valor del producto
                            print(f"El valor de producto '{getproducto} es {productos.get(getproducto)}.")
                           else:
                             print(f"El producto '{getproducto}' no existe en el inventario.")
#Modificar precio de un producto
if respuesta == 4:
          while True:
                   print("\nIngresá el nombre del producto que querés modificar precio (o presioná Enter para terminar):")
                   modificar_clave = input("Producto a modificar valor ").lower().title()
                   #Condición para salir del bucle si el código está vacío
                   if modificar_clave == "":
                      break
                   if modificar_clave in productos: #valido que este el producto para modificar su valor
                      nuevo_precio = input("Precio del Articulo: ")
                      productos[modificar_clave] = nuevo_precio
                      print(f"El precio del producto '{modificar_clave}' fue agregado del inventario.")
                   else:
                      print(f"El producto '{modificar_clave}' no existe en el inventario.")
if respuesta == 5: #agrego priducto y precio
   while True:
     print("\nIngresá el nombre del producto para inventariar:(o presioná Enter para terminar):")
     producto = input("Producto a ingresar ").lower().title()
    #Condición para salir del bucle si el código está vacío
     if producto == "":
       break
     if producto in productos:
        print(f"El producto '{producto}' ya existe en el inventario.")
     else:
       precio = input("Precio del Articulo: ")
       productos.setdefault(producto,precio)
       print(f"El producto '{producto}' fue agregado del inventario.")
# conocer todo el inventario con sus precios
if respuesta == 6:
  print("Productos disponibles: (o presioná Enter para terminar):")
  for nombre, precio in productos.items():
    print(f"{nombre.capitalize()}: ${precio}")
# Usamos keys() para ver todas las claves del diccionario
if respuesta == 7:
  print(productos.keys())

if respuesta == 8:
  print(productos.values())

if respuesta == 9:
  print(productos.items())

# Borrar todo el dicionario
if respuesta == 11:
    productos.clear()
    print("Todo el inventario fue borrado")

#productos.update() inserta otro diccionario iterando,por ej correo, edad telefono mail 8
#productos.copy() copia superficial  del diccionario
#para salir
if respuesta == 10 :
  print("Gracias por usar el programa")

 # Estado final del diccionario
print("\n--- Estado final del inventario ---")
for nombre, precio in productos.items():
   print(f"{nombre.capitalize()}: ${precio}")