# -*- coding: utf-8 -*-
"""clase 8 a modo integrador ampliado 5sep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9BbhYO3EKbriQnlu5CFAmdZ7OTa7ukD
"""

" Ejercicio clase 8 a modo integrador"
"""
programa para modificar elimnar ver y agregar prodcutos, stock y precio
de un producto en especial, en lista y de a pares
se verifica que las netradas seas enteros/float cuando se necesitya
se verifca que las entrada que deben ser solo algabeticas,lo sean
indica error en los ingresos si no estan correctos
alerta de stock bajo y precio no valido,
se puede borra todo el inventario
se pueden hacer varias tarea y salir de una tarea con un enter
se sale del programa con una opcion la 19
mostrando el inventraio actualizado con las alertas de los productos
con bajo stock y precio nuelo
"""
precio = float
stock = int
producto = str
proodcutos = {}
productos={"Interior": {"precio": 25000, "stock": 100},
           "Exoticas":{"precio": 45000, "stock": 20  },
           "Cicca":{"precio": 78000,"stock": 10},
           "Pindo": {"precio": 40000, "stock": 13},
           "Pandurata HG": {"precio": 120000, "stock": 10},
           "Alocassia": {"precio": 80000,"stock": 54},
           "Pandurata HC": {"precio": 110000, "stock": 32},
           "Platycerium" : {"precio": 87000, "stock": 44},
           "Potus": {"precio": 0, "stock": 12},
           "Alegria": {"precio": "None", "stock": 12},
           "Exterior": {"precio": 45000, "stock": 12}}
# Bucle con for para obtener si un producto teien bajo stock, si es asi, muestra un alerta
# Dentro del bucle chequeo si el precio de un articulo es nulo
for producto, detalles in productos.items():
  stock_numero = detalles["stock"]
  precio_numero = detalles["precio"]
  if stock_numero <= 10: # Chequeamos stock
      print(f"ALERTA DE STOCK.  El stock de {producto} es  bajo. {stock_numero} unidades.") # Muestro el alerta
  #else: # Stock esta ok, continuo
   #   print(f"{producto.capitalize()}: {stock_numero} unidades")
  if precio_numero == 0 or precio_numero == "None":
    print(f"ALERTA DE PRECIO.  El precio de {producto} es  nulo. $ {precio_numero} .")
  #    print(f"{producto.capitalize()}: $  {precio_numero}")
# Eleccion de operacion a realizarse
while True:
  while True:
        print(" Elige que tarea queres realizar introduciendo el numero correspondiente.")
        print(" 1. Ver Producto/Stock \n 2. Eliminar Producto \n 3. Modificar stock ")
        print(" 4. Modificar precio \n 5. Agregar producto, stock  y precio \n 6. Venta de un producto")
        print(" 7. Inventario disponible \n 8. Ver solo Productos disponibles \n  9. Stock y Precios disponibles")
        print(" 10. Muestra Stock \n 11. Muestro Precio \n 12. Precio de un producto 13. Stock de un producto")
        print(" 14. Agregar Producto \n 15 Agregar Cantidad \n  16.Agregar Precio ")
        print(" 17. Compra de un producto \n 18. Borrar Stock \n 19. Salir \n ")

#PUNTOS 14 16 15 AGREGAR producto STOCK PRECIO ES IGUAL QUE MODIFICAR PARA QUE SI ESTA MODIFICAR, ARREGLARLOS
#ARREGLAR 5  6  17
        try:
           respuesta = int(input("Respuesta: "))
           # se valida que la entrada sea numerica con el Try except y con el if
           #que el numero ingresado sea ente 1 y 18
           if respuesta >0 and respuesta < 20:
              break
           else: print(" Error. Numero fuera de rango.")
        except ValueError:
           print(" Error. Por favor ingrese solo números.")
           # Con Match determinamos las tareas a realizarse
        if not productos:
          print(" El inventario está vacío. ")
          break
# Con Match, se acceden a las diferentes opciones de manipulacion del inventario

  match respuesta:
          #con items, vemos el inventario, producto, stock y precio
         case 1:
              print(productos.items())
         # Eliminar un producto
         case 2:
                while True:
                      eliminar = input("\n Ingresá el nombre del producto que querés eliminar (o presioná Enter para terminar): ").lower().title().strip()

                      # Si el usuario presiona Enter sin escribir nada, se sale del bucle
                      if eliminar == "":
                        break
                    # VALIDARRR LETRASSSS CARACTERES NO NUMERICOS NI
                      if eliminar.isalpha():
                          if eliminar in productos:
                             productos.pop(eliminar)
                             print(f" El producto '{eliminar}' fue eliminado del inventario.")
                          else:
                             print(f" El producto '{eliminar}' no existe en el inventario.")
                      else:
                        print(" Error. Por favor ingrese solo letras.")
          # Modificar stock de un producto manualmente
         case 3:  ######################################### falta perfeccionar no vuleve a pedir reingreso stock sino el producto
              print("\n Ingresá el nombre del producto que querés modificar stock (o presioná Enter para terminar):")
              while True:

                   producto = input(" Producto a modificar stock ").lower().title().strip()
                   #Condición para salir del bucle si el código está vacío
                   if producto == "":
                      break
                   # valido carcatres alfabeticos para producto
                   if not producto.isalpha():
                     print(" Error. Por favor ingrese solo letras.")
                   else:
                     #valido que este el producto para modificar su stock
                      if producto in productos:
                        while True:
                         try:
                             nuevo_stock = int(input(" Stock del Articulo: "))
                             productos[producto]["stock"] = nuevo_stock
                             if productos[producto]["stock"] <=10:
                                print(f" Alerta! El stock de {producto} es  bajo. {nuevo_stock} unidades.")
                                pregunta = input(" Quiere mantener este stock? Y/N ").lower().strip()
                                if pregunta == "y":
                                   productos[producto]["stock"] = nuevo_stock
                                   print(f" El stock del producto '{producto}' fue modificado en el inventario.")
                                   break
                                else:
                                   print(f" El stock del producto '{producto}' no fue modificado en el inventario.")
                             else:
                                print(f" El stock del producto '{producto}' fue modificado en el inventario.")
                                break
                         except ValueError:
                                print(" Error. Por favor ingrese solo números.")
                      else:
                          print(f" El producto '{modificar_clave}' no existe en el inventario.")

          # Modificar precio de un producto manualmente
         case 4:
              print("\n Ingresá el nombre del producto que querés modificar precio (o presioná Enter para terminar):")
              while True:

                   modificar_clave = input(" Producto a modificar precio ").lower().title().strip()
                   #Condición para salir del bucle si el código está vacío
                   if modificar_clave == "":
                      break
                   # Valido que no haya carcateres numericos o especiales en el nombre del producto
                   if not modificar_clave.isalpha():
                    print(" Error. Por favor ingrese solo letras.")
                   else:
                    if modificar_clave in productos: #valido que este el producto para modificar su stock

                       while True:
                        try:
                          nuevo_precio = float(input(" Precio del Articulo: "))
                          productos[modificar_clave]['precio'] = nuevo_precio
                          if nuevo_precio < 0 or nuevo_precio =="None":
                            print(f" ALERTA. El precio del producto '{modificar_clave}' es menor a cero. No es Modificado")
                            break
                          if nuevo_precio == 0 :
                            print(f" ALERTA. El precio del producto '{modificar_clave}' es nulo. No es Modificado")
                            repuesta = input(" Quiere mantener este precio? Y/N ").lower().strip()
                            if repuesta == "y":
                               productos[modificar_clave]['precio'] = nuevo_precio
                               print(f" El precio del producto '{modificar_clave}' fue modificado en el inventario.")
                               break
                          else:
                            print(f" El precio del producto '{modificar_clave}' fue modificado en el inventario.")
                            break
                        except ValueError:
                            print(" Error. Por favor ingrese solo números.")
                    else:
                      print(f" El producto '{modificar_clave}' no existe en el inventario.")
        #agrego producto, precio y stock
         case 5:
              print("\n Ingresá el nombre del producto para inventariar:(o presioná Enter para terminar):")
              while True:
                      producto = input(" Producto a ingresar ").lower().title().strip()
                        #Condición para salir del bucle si el código está vacío
                      if producto == "":
                         break
                         # Valido que no se ingresen carcatrees numericos o especiales en el nombre del producto
                      if producto.isalpha():

                         if producto in productos:
                            print(f" El producto '{producto}' ya existe en el inventario.")
                         else:
                            try:
                               nuevo_stock = int(input(" Stock del Producto: "))
                               nuevo_precio= float (input(" Precio del Articulo: "))
                               productos.setdefault(producto, {"stock": nuevo_stock, "precio": nuevo_precio})
                        # productos[nuevo_producto = {"stock": nuevo_stock, "precio": nuevo_precio}
                               print(f" El producto y su stock '{producto}' fueron agregados en el inventario.")
                            except ValueError:
                               print(" Error.Por favor ingrese solo números para Stock y Float.")
                      else:
                        print(" Error. Por favor ingrese solo letras.")
         # Ingresamos cantidad vendida para modificar stock
         case 6:
            while True:
                      print("\n Ingresá el nombre del producto vendido:(o presioná Enter para terminar):")
                      producto_vendido = input(" Producto vendido ").lower().title().strip()
                     #Condición para salir del bucle si el código está vacío
                      if producto_vendido == "":
                         break
                      if not producto_vendido.isalpha():
                        print(" Error. Por favor ingrese solo letras.")
                      if producto_vendido in productos:
                        try:
                           venta = int(input(" Cantidad vendida: "))
                           stock_original = productos[producto_vendido]['stock']
                           stock_actualizado= stock_original - venta
                           productos[producto_vendido]['stock'] = stock_actualizado
                           print(f" El stock de '{producto_vendido}' fué modificado en el inventario.")
                        except ValueError:
                           print(" Error. Por favor ingrese solo números.")
                      else:
                        print(f" El producto '{producto_vendido}' no existe en el inventario.")
              # Mostrar el inventario disponible
         case 7:
               print(" Productos disponibles: (o presioná Enter para terminar):")
               for nombre, detalles in productos.items():
                   print(f"{nombre.capitalize()}:  ${detalles['precio']} ,{detalles['stock']} unidades")
          # Usamos keys() para ver todas las claves del diccionario osea los productos
         case 8:
              print(productos.keys())
          #usamos value() para saber solo todos los valores de stock y precios
         case 9: #
              print(productos.values())
         case 10: # vemos solo stock
           for producto, detalles in productos.items():
                  print(f"{producto.capitalize()}: {detalles['stock']} unidades")
                  if detalles["stock"] <= 10: #Con el condicionale verifico el stock bajo
                    print(f" Alerta Stock bajo de {producto}")
           #  Ver valor de un producto
         case 11: # vemos solo los precios
              for producto, detalles in productos.items():
                  print(f"{producto.capitalize()}: $ {detalles['precio']}")
                  if detalles["precio"] == 0 or detalles["precio"] == "None": #verifico si el precio es nulo 0 o None
                    print(f" Alerta Precio Nulo de {producto}")
        # Vemos el precio de un producto determinado
         case 12:
               while True:
                      print("\nIngresá el nombre del producto a saber precio (o presioná Enter para terminar):")
                      getproducto = input("Producto: ").lower().title().strip()
                      if getproducto == "":
                         break
                      # Validar que no se ingresen varactres numericos ni especiales como nombre del producto
                      if not getproducto.isalpha():
                        print(" Error. Por favor ingrese solo letras.")
                      else:
                        if getproducto in productos:
                       #se muestra el valor del producto
                          print(f"El precio de producto '{getproducto}' es ${productos[getproducto]['precio']}.")
                          if productos[getproducto]['precio'] == 0 or productos[getproducto]['precio'] == "None":
                            print(f" ALERTA. El precio de '{getproducto}' es nulo/invalido.")
                        else:
                           print(f"El producto '{getproducto}' no existe en el inventario.")
          # Ver stock de un producto determinado
         case 13:
               while True:
                      print("\nIngresá el nombre del producto a saber stock (o presioná Enter para terminar):")
                      getproducto = input("Producto: ").lower().title().strip()
                      if getproducto == "":
                         break
                      # Valido caracteres alfabeticos
                      if getproducto.isalpha():
                        if getproducto in productos:
                       #se muestra el stock del producto
                               print(f"El stock de producto '{getproducto}' es {productos[getproducto]['stock']} unidades.")
                               if productos[getproducto]['stock'] <= 10: #Con el condicionale verifico el stock bajo
                                  print(f" Alerta Stock bajo de {producto}")
                        else:
                             print(f"El producto '{getproducto}' no existe en el inventario.")
                      else:
                        print(" Error. Por favor ingrese solo letras.")
         # Agregar un producto, imprimira al final con valor None
         case 14:
               print("\nIngresá el nombre del producto que querés agregar (o presioná Enter para terminar):")
               while True:

                      incorporado = input("Producto a agregarse: ").lower() .title().strip()
                      if incorporado == "":
                         break
                      ##  verifico si es una cadena valida
                      if not incorporado.isalpha():
                        print(" Error. Por favor ingrese solo letras.")
                      else:
                         if incorporado in productos:
                            print(f"El producto '{incorporado}' ya existe en el inventario.")
                         else:
                            productos.setdefault(incorporado)
                            print(f"El producto '{incorporado}' fue agregado del inventario.")
         # Agregar un stock, imprimira al final con valor None ****************************
         case 15 :
               while True:
                      print("\nIngresá el nombre del producto que querés agregar (o presioná Enter para terminar):")
                      incorporado = input("Productoa agregarse: ").lower() .title().strip()
                      if incorporado == "":
                         break
                      #        VERIFICAR QUE SEA SOLO CADENA
                      if incorporado in productos:
                         print(f"El producto '{incorporado}' ya existe en el inventario.")
                      else:
                         productos.setdefault(incorporado)
                         print(f"El producto '{incorporado}' fue agregado del inventario.")
         # Agregar un precio **************************************
         case 16 :
               while True:
                      print("\nIngresá el nombre del producto que querés agregar (o presioná Enter para terminar):")
                      incorporado = input("Productoa agregarse: ").lower() .title().strip()
                      if incorporado == "":
                         break
                      #        VERIFICAR QUE SEA SOLO CADENA
                      if incorporado in productos:
                         print(f"El producto '{incorporado}' ya existe en el inventario.")
                      else:
                         productos.setdefault(incorporado)
                         print(f"El producto '{incorporado}' fue agregado del inventario.")
         # Nos abastecemos de unidades de un producto y lo sumamos
         case 17:
          while True:
                      producto_comprado = input("\n Ingresá el nombre del producto a actualiza stock:(o presioná Enter para terminar):").lower().title().strip()

                     #Condición para salir del bucle si el código está vacío
                      if producto_comprado == "":
                         break
                      #  Verifico que sea una cadena
                      if producto_comprado.isalpha():
                          if producto_comprado in productos:
                             try:
                                  compra = int(input(" Cantidad comprada: "))
                                  if compra > 0:
                                      stock_original = productos[producto_comprado]['stock']
                                      stock_actualizado= stock_original + compra
                                      productos[producto_comprado]['stock'] = stock_actualizado
                                      print(f" El stock de '{producto_comprado}' fué modificado en el inventario.")
                                  else:
                                       print(" Error. Por favor ingrese solo números positivos.")
                             except ValueError:
                                    print(" Error. Por favor ingrese solo números.")
                          else:
                              print(f" El producto '{producto_comprado}' no existe en el inventario.")
                      else:
                        print(" Error. Por favor ingrese solo letras.")
         # Borramos el inventario
         case 18:
             productos.clear()
             print(" Todo el inventario ha sido borrado. ")
         # Falta
         #productos.update() inserta otro diccionario iterando,por ej correo, edad telefono mail 8
         #productos.copy() copia superficial  del diccionario
         #para salir
         case 19 :
            print(" Gracias por usar el programa! ")
            break
# Estado final del diccionario
print("\n *** Estado final del Inventario ***")
# Mientras imprimimos el listado, alertamos de stock bajo y orecio nulo
for producto, detalles in productos.items():
  stock_numero = detalles["stock"]
  precio_numero = detalles["precio"]
  if stock_numero <= 10: # Chequeamos stock
      print(f"ALERTA DE STOCK.  El stock de {producto} es  bajo. {stock_numero} unidades.") # Muestro el alerta
  if  precio_numero == 0 or precio_numero == "None":
      print(f"ALERTA DE PRECIO.  El precio de {producto} es  nulo. $ {precio_numero} .")
  print(f"{producto.capitalize()}: $  {precio_numero}, {stock_numero}  unidades" )
# Eleccion de operacion a realizarse