# -*- coding: utf-8 -*-
"""clase8_Dicc_Stock_Modo_Integrador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17smQi4U6tFgM08m6guWs7utOd-wRbzsa
"""



" Ejercicio clase 8 a modo integrador"
productos={# Cremos un diccionario llamado producto con algunos articulos
           "Exterior": 100,
           "Interior": 1000,
           "Exoticas": 135,
           "Cicca": 10,
           "Pindo": 78,
           "Pandurata HG": 23,
           "Alocassia": 200,
           "Pandurata HC": 32,
           "Platycerium" : 32
}

# Alerta de stock
for producto, stock in productos.items():
   if stock <= 10:
    print(f" Alerta! El stock de {producto} es  bajo. {stock} unidades.")

# Eleccion de operacion a realizarse
while True:
  while True:
        print(" Elige que tarea queres realizar introduciendo el numero correspondiente * ")
        print("\n Eliminar productos: 1 * Agregar productos: 2 \n Ver stock del producto: 3 \n")
        print(" Modificar stock: 4 \n Agregar producto y stock: 5 \n Inventario disponible: 6 \n ")
        print(" Ver solo Productos disponibles: 7 \n Ver solo stock disponible: 8 \n Ver Prodcuto/Stock:9 \n")
        print(" Venta de un prodcuto: 10 \n Borrar Inventario: 11 \n Salir: 13 \n ")
        try:
           respuesta = int(input("Respuesta: "))
           # se valida que la entrada sea numeirica con el Try except y con el if
           #que el numero ingresado sea ente 1 y 11
           if respuesta >0 and respuesta < 13:
              break
           else: print(" Error. Numero fuera de rango.")
        except ValueError:
           print(" Error. Por favor ingrese solo números.")
           # Con Match determinamos las tareas a realizarse
          # Eliminar un producto
  match respuesta:
         case 1:
                while True:
                      print("\n Ingresá el nombre del producto que querés eliminar (o presioná Enter para terminar): ")
                      eliminar = input("Producto a eliminar: ").lower().title()

                      # Si el usuario presiona Enter sin escribir nada, se sale del bucle
                      if eliminar == "":
                        break

                      # Verificamos si el producto está en el diccionario y lo eliminamos
                      if eliminar in productos:
                        productos.pop(eliminar)
                        print(f" El producto '{eliminar}' fue eliminado del inventario.")
                      else:
                        print(f" El producto '{eliminar}' no existe en el inventario.")

         case 2: # Agregar un producto, imprimira al final con valor None
               while True:
                      print("\n Ingresá el nombre del producto que querés agregar (o presioná Enter para terminar):")
                      incorporado = input(" Producto a agregarse: ").lower() .title().strip()
                      if incorporado == "":
                         break
                      if incorporado in productos:
                         print(f" El producto '{incorporado}' ya existe en el inventario.")
                      else:
                         productos.setdefault(incorporado)
                         print(f" El producto '{incorporado}' fue agregado del inventario.")

          #  Saber valor de un producto
         case 3:
               while True:
                      print("\n Ingresá el nombre del producto a saber stock (o presioná Enter para terminar):")
                      getproducto = input(" Producto: ").lower().title().strip()
                      if getproducto == "":
                         break
                      if getproducto in productos:
                       #se muestra el valor del producto
                         print(f" El stock de producto '{getproducto} es {productos.get(getproducto)}.")
                      else:
                        print(f" El producto '{getproducto}' no existe en el inventario.")
          # Modificar stock de un producto manualmente
         case 4:
              while True:
                   print("\n Ingresá el nombre del producto que querés modificar stock (o presioná Enter para terminar):")
                   modificar_clave = input(" Producto a modificar stock ").lower().title().strip()
                   #Condición para salir del bucle si el código está vacío
                   if modificar_clave == "":
                      break
                   if modificar_clave in productos: #valido que este el producto para modificar su stock
                      nuevo_stock = int(input(" Stock del Articulo: "))
                      productos[modificar_clave] = nuevo_stock
                      print(f" El stock del producto '{modificar_clave}' fue modificado en el inventario.")
                   else:
                      print(f" El producto '{modificar_clave}' no existe en el inventario.")
         case 5: #agrego priducto y precio
              while True:
                      print("\n Ingresá el nombre del producto para inventariar:(o presioná Enter para terminar):")
                      producto = input(" Producto a ingresar ").lower().title().strip()
                     #Condición para salir del bucle si el código está vacío
                      if producto == "":
                         break
                      if producto in productos:
                         print(f" El producto '{producto}' ya existe en el inventario.")
                      else:
                         stock = input(" Stock del Producto: ")
                         productos.setdefault(producto,stock)
                         print(f" El producto y su stock '{producto}' fueron agregados en el inventario.")
          # conocer todo el inventario con sus precios
         case 6:
               print(" Productos disponibles: (o presioná Enter para terminar):")
               for nombre, stock in productos.items():
                   print(f"{nombre.capitalize()}: {stock} unidades")
          # Usamos keys() para ver todas las claves del diccionario
         case 7:
              print(productos.keys())
          #usamos value() para saber todos los valores de stock)
         case 8:
              print(productos.values())
          #con items, vemos el producto y su stock
         case 9:
              print(productos.items())
          # ingresamos valor de venta para modificar stock
         case 10:
          while True:
                      print("\n Ingresá el nombre del producto vendido:(o presioná Enter para terminar):")
                      producto_vendido = input(" Producto vendido ").lower().title().strip()
                     #Condición para salir del bucle si el código está vacío
                      if producto_vendido == "":
                         break
                      if producto_vendido in productos:
                         venta = int(input(" Cantidad vendida: "))
                         stock = productos[producto_vendido]
                         resta_stock = stock - venta
                         productos[producto_vendido] = resta_stock
                         print(f" El stock de '{producto_vendido}' fué modificado en el inventario.")
                      else:
                        print(f" El producto '{producto_vendido}' no existe en el inventario.")
         # Borramos el inventario
         case 11:
             productos.clear()
             print(" Todo el inventario ha sido borrado. ")

         #productos.update() inserta otro diccionario iterando,por ej correo, edad telefono mail 8
         #productos.copy() copia superficial  del diccionario
         #para salir
         case 12 :
            print(" Gracias por usar el programa! ")
            break

# Estado final del diccionario
print("\n *** Estado final del Inventario ***")
for producto, stock in productos.items():
  if stock <= 10: #chequeo esl stock final
      print(f" El stock de {producto} es  bajo. {stock} unidades.") #muestro el alerta
  else: #si el stock esta ok, continuo
      print(f"{producto.capitalize()}: {stock} unidades")

